name: Generate-README.md-snake

on:
  schedule:
    - cron: "0 */4 * * *" # execute every 4 hours
  workflow_run:
    workflows: ["Your-Quote-Update-Workflow-Name"] # Runs after quote update workflow
    types:
      - completed
  workflow_dispatch: # allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate snake game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }} # required
          outputs: |
            dist/github-snake.svg?color_snake=red
            dist/github-snake-dark.svg?palette=github-dark&color_snake=red
            dist/ocean.gif?color_snake=red&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
