name: Generate-README.md-snake

on:
  schedule:
    - cron: "0 */12 * * *" # execute every 12 hours
  workflow_dispatch: # allows to manually run the job at any time

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate snake game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }} # required
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
